// <auto-generated />
using System;
using EFCORE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCORE.Migrations
{
    [DbContext(typeof(AlunoContext))]
    [Migration("20201108184632_IncluirEntidade_TipoSocio")]
    partial class IncluirEntidade_TipoSocio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCORE.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("TipoSocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoSocioId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("EFCORE.Models.TipoSocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DuracaoEmMeses")
                        .HasColumnType("int");

                    b.Property<int>("TaxaDesconto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoSocios");
                });

            modelBuilder.Entity("EFCORE.Models.Aluno", b =>
                {
                    b.HasOne("EFCORE.Models.TipoSocio", "TipoSocio")
                        .WithMany()
                        .HasForeignKey("TipoSocioId");
                });
#pragma warning restore 612, 618
        }
    }
}
